/****************************************************************************
**
** Copyright (C) 2015 Emenda Nordic AB
** Author: Jacob Lärfors (jacob.larfors@emenda.eu)
**
** GNU Lesser General Public License Usage
** This file may be used under the terms of the GNU Lesser
** General Public License version 2.1 or version 3 as published by the Free
** Software Foundation and appearing in the file LICENSE.LGPLv21 and
** LICENSE.LGPLv3 included in the packaging of this file.  Please review the
** following information to ensure the GNU Lesser General Public License
** requirements will be met: https://www.gnu.org/licenses/lgpl.html and
** http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.
**
****************************************************************************/


#ifndef KLOCWORKREPORTPARSER_H
#define KLOCWORKREPORTPARSER_H

#include <QFile>
#include <QTreeWidgetItem>

namespace Klocwork {
namespace Internal {

class IssueOutputPane;

/*
 * Utility class for parsing the Klocwork report generated by an analysis
 */
class KlocworkReportParser
{
public:
    KlocworkReportParser();

    void parseReport(IssueOutputPane *outputPane, QFile &report, QTreeWidgetItem *parent);
};

} // namespace Internal
} // namespace KlocworkPlugin

#endif // KLOCWORKREPORTPARSER_H
